name: Code style checks
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff check
        run: ruff check --output-format=github .
      - name: Run Ruff format --check
        run: ruff format --check --diff .
